const HomeProduct =[
    {
        img:"https://i.postimg.cc/YC3qqp7d/HP.jpg",
        name:"Hp 15s, 11 th Gen Intel Core i5-8GB RAM/512GB SSD 15.6 inches Laptop....",
        category:"Laptop",
        dis_price:"Rs.22396",
        org_price:"Rs.55,990",
        save_price:"Rs.33,594",
    },
    {
        img:"https://i.postimg.cc/xjwSpWn1/HP-Pavilion.jpg",
        name:"HP Pavilion 15 11th Gen Intel core i5-8GB RAM/512GB SSD 15.6 inch(39.6 ch) Laptop,FH.....",
        category:"Laptop",
        dis_price:"Rs.24,796",
        org_price:"Rs.61,990",
        save_price:"Rs.37,194",
    },
    {
        img:"https://i.postimg.cc/vBSQ3zvF/Apple-Mac-Book-Pro-2021.jpg",
        name:"2021 Apple MacBook Pro 14-inch/35.97cm,Apple M1 Pro chip with 8-core CPU and...",
        category:"Laptop",
        dis_price:"Rs.77,960",
        org_price:"Rs.1,94,900",
        save_price:"Rs.116,940",
    },
    {
        img:"https://i.postimg.cc/vTyTc6nx/Apple-i-Phone-13.jpg",
        name:"Apple iPhone 13 (256GB) - Starlight",
        category:"Mobile",
        dis_price:"Rs.33,960",
        org_price:"Rs.84,900",
        save_price:"Rs.50,940",
    },
    {
        img:"https://i.postimg.cc/KY8FRD4M/Apple-i-Phone-12.jpg",
        name:"Apple iPhone 12(64GB) - Blue",
        category:"Mobile",
        dis_price:"Rs.21,599.6",
        org_price:"Rs.53,999",
        save_price:"Rs32,399.4",
    },
    {
        img:"https://i.postimg.cc/7ZYSXb6y/Samsung-Galaxy.jpg",
        name:"Samsung Galaxy M52 5G (Blazing Black, 6GB RAM 128 GB Storage) Latest.....",
        category:"Mobile",
        dis_price:"Rs.9,999.6",
        org_price:"Rs.24,999",
        save_price:"Rs.14,999.4",
    },
    {
        img:"https://i.postimg.cc/vBMqvf4t/Centage-JEE.jpg",
        name:"Centage JEE Advanced Maths for 2021 - Set of 5 Books - Latest Revised Editors",
        category:"Book",
        dis_price:"Rs.1,027.6",
        org_price:"Rs.2,569",
        save_price:"Rs.1,541.4",
    },
    {
        img:"https://i.postimg.cc/RhhTPR4K/Complete-Mathematics.jpg",
        name:"Complete Mathematics for JEE  Main 2021",
        category:"Book",
        dis_price:"Rs.246",
        org_price:"Rs.615",
        save_price:"Rs.369",
    },
    {
        img:"https://i.postimg.cc/qqHmY6Bj/Master-Resource-Book-in-Physics.jpg",
        name:"Master Resource Book in Physics for JEE Main 2022",
        category:"Book",
        dis_price:"Rs.232",
        org_price:"Rs.580",
        save_price:"Rs.348",
    },
]
export default HomeProduct;