const Productdata =[
    {
        img:"https://i.postimg.cc/YC3qqp7d/HP.jpg",
        name:"Hp 15s, 11 th Gen Intel Core i5-8GB RAM/512GB SSD 15.6 inches Laptop....",
        category:"Laptop",
        dis_price:"Rs.22396",
        org_price:"Rs.55,990",
        save_price:"Rs.33,594",
    },
    {
        img:"https://i.postimg.cc/xjwSpWn1/HP-Pavilion.jpg",
        name:"HP Pavilion 15 11th Gen Intel core i5-8GB RAM/512GB SSD 15.6 inch(39.6 ch) Laptop,FH.....",
        category:"Laptop",
        dis_price:"Rs.24,796",
        org_price:"Rs.61,990",
        save_price:"Rs.37,194",
    },
    {
        img:"https://i.postimg.cc/vBSQ3zvF/Apple-Mac-Book-Pro-2021.jpg",
        name:"2021 Apple MacBook Pro 14-inch/35.97cm,Apple M1 Pro chip with 8-core CPU and...",
        category:"Laptop",
        dis_price:"Rs.77,960",
        org_price:"Rs.1,94,900",
        save_price:"Rs.116,940",
    },
    {
        img:"https://i.postimg.cc/0QggQBZN/Apple-Mac-Book-Pro-2020.jpg",
        name:"2020 Apple MacBook Pro 13.3inch/33.78 cm Apple M1 chip with 8-core CPU and 8-core.....",
        category:"Laptop",
        dis_price:"Rs.44,396",
        org_price:"Rs.1,10,990",
        save_price:"Rs.66,594",
    },
    {
        img:"https://i.postimg.cc/R0hpc5XR/Apple-Mac-Book-Pro-14inch.jpg",
        name:"2021 Apple MacBook Pro 14-inch/35.97cm, Apple M1 Pro chip with 8-core CPU and...",
        category:"Laptop",
        dis_price:"Rs.77,960",
        org_price:"Rs.1,94,900",
        save_price:"Rs.116,940",
    },
    {
        img:"https://i.postimg.cc/X70sJyF4/Apple-Mac-Book-Air-Laptop.jpg",
        name:"2020 Apple MAcBook Air Laptop: Apple M1 chip, 13.3-inch/33.74 cm Retina Display....",
        category:"Laptop",
        dis_price:"Rs.42,396",
        org_price:"Rs.1,05,990",
        save_price:"Rs.63,594",
    },
    {
        img:"https://i.postimg.cc/yYLggw5n/Lenovo-Idea-Pad-Slim-3.jpg",
        name:"Lenovo IdeaPad 3 11th Gen Intel Core i5 15.6 inches FHD Thin and Light Laptop....",
        category:"Laptop",
        dis_price:"Rs.21,996",
        org_price:"Rs.54,990",
        save_price:"Rs.32,994",
    },
    {
        img:"https://i.postimg.cc/vTyTc6nx/Apple-i-Phone-13.jpg",
        name:"Apple iPhone 13 (256GB) - Starlight",
        category:"Mobile",
        dis_price:"Rs.33,960",
        org_price:"Rs.84,900",
        save_price:"Rs.50,940",
    },
    {
        img:"https://i.postimg.cc/dtpfcmcB/Apple-1-Phone-13-Mini.jpg",
        name:"Apple iPhone 13 Mini(128 GB) - Pink",
        category:"Mobile",
        dis_price:"Rs.27,960",
        org_price:"Rs.69,900",
        save_price:"Rs.41,940",
    },
    {
        img:"https://i.postimg.cc/KY8FRD4M/Apple-i-Phone-12.jpg",
        name:"Apple iPhone 12(64GB) - Blue",
        category:"Mobile",
        dis_price:"Rs.21,599.6",
        org_price:"Rs.53,999",
        save_price:"Rs32,399.4",
    },
    {
        img:"https://i.postimg.cc/h41BbYxd/Apple-i-Phone-XR.jpg",
        name:"Apple iPhone XR (64GB) - (Product) Red",
        category:"Mobile",
        dis_price:"Rs.15,199.6",
        org_price:"Rs.37,999",
        save_price:"Rs.22,799.4",
    },
    {
        img:"https://i.postimg.cc/7ZYSXb6y/Samsung-Galaxy.jpg",
        name:"Samsung Galaxy M52 5G (Blazing Black, 6GB RAM 128 GB Storage) Latest.....",
        category:"Mobile",
        dis_price:"Rs.9,999.6",
        org_price:"Rs.24,999",
        save_price:"Rs.14,999.4",
    },
    {
        img:"https://i.postimg.cc/vBMqvf4t/Centage-JEE.jpg",
        name:"Centage JEE Advanced Maths for 2021 - Set of 5 Books - Latest Revised Editors",
        category:"Book",
        dis_price:"Rs.1,027.6",
        org_price:"Rs.2,569",
        save_price:"Rs.1,541.4",
    },
    {
        img:"https://i.postimg.cc/RhhTPR4K/Complete-Mathematics.jpg",
        name:"Complete Mathematics for JEE  Main 2021",
        category:"Book",
        dis_price:"Rs.246",
        org_price:"Rs.615",
        save_price:"Rs.369",
    },
    {
        img:"https://i.postimg.cc/CK4HStKb/IIT-JEE.jpg",
        name:"IIT- JEE (Mains and Advanced) 41 - Years Sets If 3 - Books (Chem. + Phy. +Maths.) Chapterwise..",
        category:"Book",
        dis_price:"Rs.350",
        org_price:"Rs.875",
        save_price:"Rs.525",
    },
    {
        img:"https://i.postimg.cc/Nfh48RZ9/Short-Tricks.jpg",
        name:"Short Tricks in Mathematics for IIT JEE Main and Advanced 2021 - 22 By Career Point Kota",
        category:"Book",
        dis_price:"Rs.149.2",
        org_price:"Rs.373",
        save_price:"Rs.223.8",
    },
    {
        img:"https://i.postimg.cc/Wz00YfxD/Solved-Papers.jpg",
        name:"43 Years Chapterwise Topicwise Solved Papers (2019 - 1979) IIT JEE (PCM) PHYSICS...",
        category:"Book",
        dis_price:"Rs.123.6",
        org_price:"Rs.309",
        save_price:"Rs.185.4",
    },
    {
        img:"https://i.postimg.cc/BbFrPGbw/Handbook-of-Physics-Formulae.jpg",
        name:"Handbook of Physics Formulae for IIT JEE and NEET- UG 2021 - 2022 By Career Point Kota",
        category:"Book",
        dis_price:"",
        org_price:"Rs.150",
        save_price:"",
    },
    {
        img:"https://i.postimg.cc/qqHmY6Bj/Master-Resource-Book-in-Physics.jpg",
        name:"Master Resource Book in Physics for JEE Main 2022",
        category:"Book",
        dis_price:"Rs.232",
        org_price:"Rs.580",
        save_price:"Rs.348",
    },
    {
        img:"https://i.postimg.cc/CKfsgMQt/Physics-Solved-Papers.jpg",
        name:"43 Years Chapterwise Topicwise Solved Papers(2021 - 1979) IIT JEE Physics",
        category:"Book",
        dis_price:"Rs.101.6",
        org_price:"Rs.254",
        save_price:"Rs.152.4",
    },
]
export default Productdata;